### ISSUE TITLE
Unable to run the docker-compose successfully

### ISSUE THREAD

**Issue by kpachhai** [BenSchZA/docker-android-avd#6]
Looks like I'm getting some errors while trying to run this the first time:

```
Successfully built 86a4cf5d8020
Successfully tagged vm:latest
Starting docker-android-avd_vm_1 ... done
Attaching to docker-android-avd_vm_1
vm_1  | stored passwd in file: /.password2
vm_1  | * enable HTTP base authentication
vm_1  | Adding password for user root
vm_1  | ln: failed to create symbolic link '/usr/local/lib/web/frontend/static/novnc/utils/websockify/websockify': File exists
vm_1  | 2020-03-25 13:55:12,361 CRIT Supervisor running as root (no user in config file)
vm_1  | 2020-03-25 13:55:12,362 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
vm_1  | Unlinking stale socket /var/run/supervisor.sock
vm_1  | 2020-03-25 13:55:12,680 INFO RPC interface 'supervisor' initialized
vm_1  | 2020-03-25 13:55:12,680 CRIT Server 'unix_http_server' running without any HTTP authentication checking
vm_1  | 2020-03-25 13:55:12,680 INFO supervisord started with pid 20
vm_1  | 2020-03-25 13:55:13,687 INFO spawned: 'nginx' with pid 23
vm_1  | 2020-03-25 13:55:13,688 INFO spawned: 'android-avd' with pid 24
vm_1  | 2020-03-25 13:55:13,691 INFO spawned: 'web' with pid 25
vm_1  | 2020-03-25 13:55:13,692 INFO spawned: 'novnc' with pid 26
vm_1  | 2020-03-25 13:55:13,693 INFO spawned: 'wm' with pid 27
vm_1  | 2020-03-25 13:55:13,694 INFO spawned: 'pcmanfm' with pid 29
vm_1  | 2020-03-25 13:55:13,695 INFO spawned: 'lxpanel' with pid 30
vm_1  | 2020-03-25 13:55:13,696 INFO spawned: 'xvfb' with pid 31
vm_1  | 2020-03-25 13:55:13,697 INFO spawned: 'x11vnc' with pid 32
vm_1  | 2020-03-25 13:55:13,724 INFO exited: x11vnc (exit status 1; not expected)
vm_1  | 2020-03-25 13:55:13,821 INFO exited: nginx (exit status 1; not expected)
vm_1  | 2020-03-25 13:55:14,206 INFO  Listening on http://localhost:6079 (run.py:87)
vm_1  | 2020-03-25 13:55:15,046 INFO spawned: 'nginx' with pid 67
vm_1  | 2020-03-25 13:55:15,046 INFO success: android-avd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,046 INFO success: web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,046 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,047 INFO success: wm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,047 INFO success: pcmanfm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,047 INFO success: lxpanel entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,047 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:15,048 INFO spawned: 'x11vnc' with pid 69
vm_1  | 2020-03-25 13:55:15,055 INFO exited: nginx (exit status 1; not expected)
vm_1  | 2020-03-25 13:55:16,089 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vm_1  | 2020-03-25 13:55:17,092 INFO spawned: 'nginx' with pid 70
vm_1  | 2020-03-25 13:55:17,100 INFO exited: nginx (exit status 1; not expected)
vm_1  | 2020-03-25 13:55:20,106 INFO spawned: 'nginx' with pid 72
vm_1  | 2020-03-25 13:55:20,114 INFO exited: nginx (exit status 1; not expected)
vm_1  | 2020-03-25 13:55:21,115 INFO gave up: nginx entered FATAL state, too many start retries too quickly
vm_1  | 2020-03-25 13:55:29,142 INFO exited: android-avd (exit status 0; expected)
```

**Comment by kpachhai** [comment]
Any update on this?

**Comment by kpachhai** [comment]
Does anyone even maintain this repo? Or is it dead?

**Comment by BenSchZA** [comment]
@kpachhai Sorry for the late reply. I've never seen this error, and don't have time at the moment to try recreate it.

**Comment by BenSchZA** [comment]
@kpachhai This is an open-source project, so if you find a fix, please let us know. It would be very helpful if you gave further details about your machine, software, how you tried to fix it, etc.

**Comment by kpachhai** [comment]
@BenSchZA Thanks for checking. As far as what I'm running this under:
- Ubuntu inside my virtualbox on a windows desktop

**Comment by BenSchZA** [comment]
Does the issue still happen / was it repeatable?

**Comment by kpachhai** [comment]
Yes. This issue is still happening unfortunately. I have the same issue when trying to run on my Mac too

**Comment by ctoveloz** [comment]
i have the same issue im my vps with ubuntu 18 and kvm enabled

**Comment by galihanggara68** [comment]
I have the same issue but with different error log :
```Starting wa-avd-docker_vm_1 ...

ERROR: for wa-avd-docker_vm_1  a bytes-like object is required, not 'str'

ERROR: for vm  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/9b970f431bcc399bfb3cef5b8036bb5e602a055f2889f7ec66f0d290202181b0/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint wa-avd-docker_vm_1 (2de5214891a903f437e3c5cc159a0a16432fe8e37281746f08fad22848235500): Error starting userland proxy: listen tcp 0.0.0.0:5900: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 567, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 506, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 508, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 620, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
